language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  - coverage run -m unittest discover

after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master